#!/bin/false

## THIS SCRIPT WILL BE SOURCED by the make-*.sh scripts
## Do not execute directly!

WALLMATOR_scriptheader="\
#!/bin/false

## THIS SCRIPT IS AUTOGENERATED BY $0 on $(date +'%Y-%m-%d %H:%M:%S.%N')
## Do not edit directly!

## THIS SCRIPT WILL BE SOURCED BY wallmator.sh
## Do not execute directly!
"

WALLMATOR_scriptfooter="\
WALLMATOR_STAGECOMPLETE

## WARNING!! DO *NOT* END WITH 'exit 0'!!!
## This script is sourced!
"

## THIS FILE IS SOURCED!!
## DO NOT END WITH exit !!!

